backend/silownia_project/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from django.contrib import admin
from silownia_app import views
from silownia_app.views import edit_membership, add_event, list_events, user_login, delete_event, select_client_for_event, add_client_to_personal_event, list_clients_for_event, remove_client_from_event

urlpatterns = [
    path('', views.index, name='index'),
    path('clients/', views.list_clients, name='list_clients'),
    path('clients/list/', views.list_clients, name='list_clients'),
    path('clients/add/', views.add_client, name='add_client'),
    path('clients/delete/<int:client_id>/', views.delete_client, name='delete_client'),
    path('memberships/list/', views.list_memberships, name='list_memberships'),
    path('memberships/add/', views.add_membership, name='add_membership'),
    path('memberships/delete/<int:membership_id>/', views.delete_membership, name='delete_membership'),
    path('memberships/edit/<int:membership_id>/', edit_membership, name='edit_membership'),
    path('events/add/', add_event, name='add_event'),
    path('events/list/', list_events, name='list_events'),
    path('login/', user_login, name='user_login'),
    path('events/add/', add_event, name='add_event'),
    path('events/add_group/', views.add_group_event, name='add_group_event'),
    path('events/list_group/', views.list_group_events, name='list_group_events'),
    path('events/list_personal_schedules/', views.list_personal_schedules, name='list_personal_schedules'),
    path('select_client/<int:event_id>/', select_client_for_event, name='select_client_for_event'),
    path('add_client_to_personal_event/<int:event_id>/', add_client_to_personal_event, name='add_client_to_personal_event'),
    path('enroll_group_event/<int:event_id>/', views.enroll_for_group_event, name='enroll_for_group_event'),
    path('events/delete/<int:event_id>/', delete_event, name='delete_event'),
    path('logout/', views.user_logout, name='user_logout'),
    path('list_clients_for_event/<int:event_id>/', list_clients_for_event, name='list_clients_for_event'),
    path('remove_client_from_event/<int:event_id>/<int:client_id>/', remove_client_from_event, name='remove_client_from_event'),
]

backend/silownia_app/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages


class ClientManager(BaseUserManager):
    def create_user(self, login, password=None):
        if not login:
            raise ValueError(_('Użytkownik musi mieć login'))

        user = self.model(
            login=login,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, login, password):
        user = self.create_user(
            login,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class Client(AbstractBaseUser):
    login = models.CharField(_('login'), max_length=100, unique=True)
    first_name = models.CharField(_('imię'), max_length=100)
    last_name = models.CharField(_('nazwisko'), max_length=100)
    date_of_birth = models.DateField(_('data urodzenia'), null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)
    is_trainer = models.BooleanField(default=False)

    objects = ClientManager()

    USERNAME_FIELD = 'login'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.login
    
    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

# Model karnetu
class Membership(models.Model):
    MEMBERSHIP_CHOICES = [
        ('Normal', _('Normal')),
        ('Premium', _('Premium')),
    ]

    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    activation_date = models.DateField()
    expiration_date = models.DateField()
    membership_type = models.CharField(
        max_length=10,
        choices=MEMBERSHIP_CHOICES,
        default='Normal',
    )

    def __str__(self):
        return f"{self.get_membership_type_display()} - {self.client.login}"

# Model wydarzenia
class Event(models.Model):
    date = models.DateTimeField()
    trainer = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True, related_name='trainer_events')
    EVENT_TYPE_CHOICES = [
        ('group', 'Trening grupowy'),
        ('personal', 'Trening personalny'),
    ]
    event_type = models.CharField(max_length=20, choices=EVENT_TYPE_CHOICES)
    max_clients = models.PositiveIntegerField(default=1)
    clients_list = models.ManyToManyField('Client', blank=True, related_name='client_events')

    def get_current_registered_clients_count(self):
        return self.eventregistration_set.count()

    

# Model zapisów na wydarzenia
class EventRegistration(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

backend/silownia_app/views.py
# views.py w silownia_app

from django.shortcuts import render, redirect, get_object_or_404
from .models import Client, Membership, Event, EventRegistration
from .forms import ClientForm, Membership, MembershipForm, MembershipEditForm, EventForm, GroupEventForm, \
    TrainerSelectForm, ClientSelectForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
import logging
from django.contrib.auth.decorators import user_passes_test, login_required
from .forms import ClientAuthenticationForm
@login_required(login_url='user_login')
def index(request):
    user_role = None

    if request.user.is_authenticated:
        if request.user.is_employee:
            user_role = 'employee'
        elif request.user.is_trainer:
            user_role = 'trainer'
        elif request.user.is_admin:
            user_role = 'admin'

        # Dodaj poniższy kod, aby uzyskać karnety użytkownika
        user_memberships = Membership.objects.filter(client=request.user)
        context = {'user_role': user_role, 'user_memberships': user_memberships}
    else:
        context = {'user_role': user_role}

    return render(request, 'index.html', context)


@user_passes_test(lambda user: user.is_active and (user.is_employee or user.is_admin), login_url='user_login')
def list_clients(request):
    clients = Client.objects.all()
    return render(request, 'clients/list.html', {'clients': clients, 'home_url': 'home'})


@user_passes_test(lambda user: user.is_active and (user.is_employee or user.is_admin), login_url='user_login')
def add_client(request):
    if request.method == 'POST':
        # Pass the user's role to the form
        form = ClientForm(request.POST, user_role='admin' if request.user.is_admin else 'employee')

        if form.is_valid():
            form.save()
            return redirect('list_clients')
    else:
        # Pass the user's role to the form
        form = ClientForm(user_role='admin' if request.user.is_admin else 'employee')

    return render(request, 'clients/add.html', {'form': form, 'home_url': 'home'})

@user_passes_test(lambda user: user.is_active and (user.is_employee or user.is_admin), login_url='login')
def delete_client(request, client_id):
    client = Client.objects.get(id=client_id)
    client.delete()
    return redirect('list_clients')

@user_passes_test(lambda user: user.is_active and (user.is_employee or user.is_admin), login_url='user_login')
def add_membership(request):
    if request.method == 'POST':
        form = MembershipForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('list_memberships')
    else:
        form = MembershipForm()

    return render(request, 'memberships/add.html', {'form': form, 'home_url': 'home'})

@user_passes_test(lambda user: user.is_active and (user.is_employee or user.is_admin), login_url='user_login')
def delete_membership(request, membership_id):
    membership = Membership.objects.get(id=membership_id)
    membership.delete()
    return redirect('list_memberships')

@user_passes_test(lambda user: user.is_active and (user.is_employee or user.is_admin), login_url='user_login')
def list_memberships(request):
    clients_with_memberships = Client.objects.prefetch_related('membership_set').all()
    return render(request, 'memberships/list.html', {'clients': clients_with_memberships})

@user_passes_test(lambda user: user.is_active and (user.is_employee or user.is_admin), login_url='user_login')
def edit_membership(request, membership_id):
    membership = get_object_or_404(Membership, id=membership_id)

    if request.method == 'POST':
        form = MembershipEditForm(request.POST, instance=membership)
        if form.is_valid():
            form.save()
            return redirect('list_memberships')
    else:
        form = MembershipEditForm(instance=membership)

    return render(request, 'memberships/edit.html', {'form': form, 'membership': membership})

@user_passes_test(lambda user: user.is_active and (user.is_trainer or user.is_admin), login_url='user_login')
def add_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.trainer = request.user  # Przypisz zalogowanego trenera
            event.save()
            return redirect('list_events')
    else:
        form = EventForm()

    return render(request, 'events/add.html', {'form': form})

@user_passes_test(lambda user: user.is_active and (user.is_employee or user.is_admin), login_url='user_login')
def add_group_event(request):
    if request.method == 'POST':
        form = GroupEventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.event_type = 'group'
            event.save()
            return redirect('list_events')
    else:
        form = GroupEventForm()

    return render(request, 'events/add_group.html', {'form': form})



def list_events(request):
    events = Event.objects.all().order_by('date')  # Sort events by date
    context = {'events': events}
    return render(request, 'events/list.html', context)

def get_group_events():
    group_events = Event.objects.filter(event_type='group').order_by('date')  # Sort group events by date
    return group_events

def list_group_events(request):
    group_events = get_group_events()
    user_is_registered = {event.id: request.user.eventregistration_set.filter(event=event).exists() for event in group_events}
    print(f'{user_is_registered}')
    return render(request, 'events/list_group.html', {'group_events': group_events, 'user_is_registered': user_is_registered})


def list_personal_schedules(request):
    form = TrainerSelectForm(request.GET)

    # Pobierz wszystkich trenerów, aby wyświetlić ich w formularzu
    trainers = Client.objects.filter(is_trainer=True)

    personal_events = Event.objects.filter(event_type='personal')

    if form.is_valid():
        trainer = form.cleaned_data['trainer']
        personal_events = personal_events.filter(trainer=trainer)

    return render(request, 'events/list_personal_schedules.html',
                  {'form': form, 'trainers': trainers, 'personal_events': personal_events})


@user_passes_test(lambda user: user.is_active and (user.is_employee or user.is_admin or user.is_trainer), login_url='user_login')
def delete_event(request, event_id):
    event = Event.objects.get(id=event_id)

    # Check if the user has permission to delete the event
    if not (request.user.is_admin or request.user == event.trainer):
        return redirect('list_events')

    event.delete()
    return redirect('list_events')

def show_user_credentials(request):
    users = Client.objects.all()
    return render(request, 'show_user_credentials.html', {'users': users})


def user_login(request):
    if request.method == 'POST':
        login_value = request.POST['login']
        password = request.POST['password']
        user = authenticate(request, login=login_value, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'Login successful')
            return redirect('index')
        else:
            messages.error(request, 'Invalid login credentials')
            logging.error(f'Login failed for user: {login_value}')

    return render(request, 'registration/login.html')

def has_employee_role(user):
    return user.is_authenticated and user.is_employee

def has_trainer_role(user):
    return user.is_authenticated and user.is_trainer

def has_admin_role(user):
    return user.is_authenticated and user.is_admin

def user_logout(request):
    logout(request)
    return redirect('user_login')

@login_required(login_url='user_login')
def enroll_for_group_event(request, event_id):
    event = get_object_or_404(Event, id=event_id, event_type='group')
    client = request.user  # Bezpośrednio używaj request.user jako klienta

    # Sprawdź, czy klient już nie jest zapisany na to wydarzenie
    if EventRegistration.objects.filter(client=client, event=event).exists():
        # Tutaj możesz obsłużyć sytuację, gdy klient już jest zapisany
        # Na przykład przekierować klienta z komunikatem
        messages.warning(request, 'Jesteś już zapisany na te zajęcia.')
        return redirect('list_group_events')

    # Tworzenie nowego wpisu o zapisie klienta na wydarzenie grupowe
    EventRegistration.objects.create(client=client, event=event)

    return redirect('list_group_events')


@login_required(login_url='user_login')
def select_client_for_event(request, event_id):
    event = get_object_or_404(Event, id=event_id, event_type='personal', trainer=request.user)

    if request.method == 'POST':
        form = ClientSelectForm(request.POST)
        if form.is_valid():
            selected_client_id = form.cleaned_data['selected_client']
            selected_client = get_object_or_404(Client, id=selected_client_id)
            event.clients.add(selected_client.id)  # Dodaj identyfikator klienta
            return redirect('list_events')
    else:
        form = ClientSelectForm()

    return render(request, 'events/select_client.html', {'form': form, 'event': event})


@login_required(login_url='user_login')
@user_passes_test(lambda user: user.is_active and (user.is_admin or user.is_trainer), login_url='user_login')
def add_client_to_personal_event(request, event_id):
    event = get_object_or_404(Event, id=event_id, event_type='personal', trainer=request.user)

    if request.method == 'POST':
        form = ClientSelectForm(request.POST)
        if form.is_valid():
            selected_client_id = form.cleaned_data['selected_client'].id
            selected_client = get_object_or_404(Client, id=selected_client_id)

            # Sprawdź, czy liczba zapisanych klientów nie przekracza max_clients
            if event.get_current_registered_clients_count() < event.max_clients:

backend/silownia_app/templates/events/add.html
<!-- events/add.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Dodaj Wydarzenie</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css_files/add2.css' %}">
</head>
<body>
    <h1>Dodaj Wydarzenie</h1>
    <form method="post" action="{% url 'add_event' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Dodaj Wydarzenie</button>
    </form>



    <nav>
        <a href="{% url 'list_events' %}">Lista Wydarzeń</a>
    </nav>
    <nav>
        <a href="{% url 'index' %}">Strona Główna</a>
    </nav>

</body>
</html>

backend/silownia_app/templates/events/add_group.html
<!-- add_group_event.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dodaj Wydarzenie Grupowe</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css_files/add_group.css' %}">
</head>
<body>
    <h1>Dodaj Wydarzenie Grupowe</h1>

    <form method="post" action="{% url 'add_group_event' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Dodaj Wydarzenie</button>
    </form>

    <a href="{% url 'list_events' %}">Powrót do Listy Wydarzeń</a>
    <nav>
        <a href="{% url 'index' %}">Strona Główna</a>
    </nav>
</body>
</html>

backend/silownia_app/templates/events/list.html
<!-- events/list.html -->
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html>
<head>
    <title>Lista Wydarzeń</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css_files/list2.css' %}">
</head>
<body>
    <h1>Lista Wydarzeń</h1>
    <main>
        <ul>
            {% for event in events %}
                <li>
                    <strong>Data:</strong> {{ event.date|date:"d.m.Y" }}<br>
                    <strong>Godzina rozpoczęcia:</strong> {{ event.date|time:"H:i" }}<br>
                    <strong>Czas trwania:</strong> 1 godzina<br>
                    <strong>Trener:</strong> {{ event.trainer.first_name }} {{ event.trainer.last_name }}<br>
                    {% if event.event_type == 'group' %}
                        <strong>Rodzaj treningu:</strong> Trening grupowy<br>

                        {% if user.is_authenticated and not user.is_admin and not user.is_employee and not user.is_trainer %}
                            {% with event_id=event.id %}
                                {% if not user_is_registered|lookup:event_id %}
                                    {% if event.get_current_registered_clients_count < event.max_clients %}
                                        <p><a href="{% url 'enroll_for_group_event' event_id %}">Zapisz się</a></p>
                                    {% else %}
                                        <p>Maksymalna liczba uczestników osiągnięta. Nie można się zapisać.</p>
                                    {% endif %}
                                {% else %}
                                    <p>Jesteś już zapisany na te zajęcia.</p>
                                {% endif %}
                            {% endwith %}
                        {% endif %}
                    {% else %}
                        <!-- Additional details for non-group events if needed -->
                        <strong>Rodzaj wydarzenia:</strong> {{ event.get_event_type_display }}<br>
                    {% endif %}
                    {% if event.event_type == 'personal' and user == event.trainer %}
                        <a href="{% url 'select_client_for_event' event.id %}" class="blue-link">Zapisz klienta</a>
                        <a href="{% url 'list_clients_for_event' event.id %}" class="blue-link">Lista Klientów</a>
                    {% endif %}
                    {% if user.is_admin or user.is_employee or user == event.trainer %}
                        <a href="{% url 'delete_event' event.id %}">Usuń</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </main>
    <nav>
        <a href="{% url 'add_event' %}">Dodaj Wydarzenie</a>
        <a href="{% url 'index' %}">Strona Główna</a>
    </nav>
</body>
</html>

backend/silownia_app/templates/events/list_clients_for_event.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista klientów zapisanych na to wydarzenie</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css_files/list2.css' %}">
</head>
<body>
  <h2>Lista klientów zapisanych na trening</h2>
  <p><strong>Data:</strong> {{ event.date|date:"d.m.Y" }}</p>
  <p><strong>Trener:</strong> {{ event.trainer.first_name }} {{ event.trainer.last_name }}</p>

  <ul>
    {% for registration in registered_clients %}
      <li>
        {{ registration.client.first_name }} {{ registration.client.last_name }}
        <a href="{% url 'remove_client_from_event' event.id registration.client.id %}">Usuń</a>
      </li>
    {% endfor %}
  </ul>
<a href="{% url 'list_events' %}">Powrót do Listy Wydarzeń</a>
    <nav>
        <a href="{% url 'index' %}">Strona Główna</a>
    </nav>
</body>
</html>

backend/silownia_app/templates/events/list_group.html
<!-- events/list_group.html -->
{% load static %}
{% load custom_filters %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista Treningów Grupowych</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css_files/list_group.css' %}">
</head>
<body>
    <header>
        <h1>Lista Treningów Grupowych</h1>
    </header>
    <main>
        <ul>
            {% if group_events %}
                {% for group_event in group_events %}
                    <li>
                        <strong>Data:</strong> {{ group_event.date|date:"d.m.Y" }}<br>
                        <strong>Godzina rozpoczęcia:</strong> {{ group_event.date|time:"H:i" }}<br>
                        <strong>Czas trwania:</strong> 1 godzina<br>
                        <strong>Trener:</strong> {{ group_event.trainer.first_name }} {{ group_event.trainer.last_name }}<br>
                        <strong>Rodzaj treningu:</strong> Trening grupowy<br>

                        {% if user.is_authenticated and not user.is_admin and not user.is_employee and not user.is_trainer %}
                            {% with event_id=group_event.id %}
                                {% if not user_is_registered|lookup:event_id %}
                                    {% if group_event.get_current_registered_clients_count < group_event.max_clients %}
                                        <p><a href="{% url 'enroll_for_group_event' event_id %}">Zapisz się</a></p>
                                    {% else %}
                                        <p>Maksymalna liczba uczestników osiągnięta. Nie można się zapisać.</p>
                                    {% endif %}
                                {% else %}
                                    <p>Jesteś już zapisany na te zajęcia.</p>
                                {% endif %}
                            {% endwith %}
                        {% endif %}
                    </li>
                {% endfor %}
            {% else %}
                <p>Brak dostępnych wydarzeń grupowych.</p>
            {% endif %}
        </ul>
    </main>
    <nav>
        <a href="{% url 'index' %}">Strona Główna</a>
    </nav>
</body>
</html>

backend/silownia_app/templates/events/list_personal_schedules.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista Grafików Trenerów Personalnych</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css_files/list_personal_schedules.css' %}">
</head>
<body>
    <h1>Lista Grafików Trenerów Personalnych</h1>

    <!-- Formularz do wyboru trenera -->
    <form method="get" action="{% url 'list_personal_schedules' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Filtruj</button>
    </form>

    <main>
        <ul>
            {% for personal_event in personal_events %}
                <li>
                    <strong>Data:</strong> {{ personal_event.date|date:"d.m.Y" }}<br>
                    <strong>Godzina rozpoczęcia:</strong> {{ personal_event.date|time:"H:i" }}<br>
                    <strong>Czas trwania:</strong> 1 godzina<br>
                    <strong>Trener:</strong> {{ personal_event.trainer.first_name }} {{ personal_event.trainer.last_name }}<br>
                    <strong>Rodzaj treningu:</strong> Trening personalny<br>
                    <!-- Dodaj dowolne dodatkowe informacje o treningu personalnym -->

                    {% if user.is_authenticated and not user.is_admin and not user.is_employee and not user.is_trainer %}
                        <!-- Dodaj obsługę zapisów na trening personalny, jeśli potrzebujesz -->
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </main>
    <nav>
        <a href="{% url 'index' %}">Strona Główna</a>
    </nav>
</body>
</html>

backend/silownia_app/templates/events/select_client.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wybierz klienta</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css_files/add2.css' %}">
</head>
<body>
  <h1>Wybierz klienta</h1>
  <form method="post" action="{% url 'add_client_to_personal_event' event.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Dodaj klienta</button>
  </form>
</body>
</html>